name: Sync with Hugging Face Space

on:
  push:
    branches:
      - main
      - master

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          export GIT_TERMINAL_PROMPT=0
          git remote remove space || true
          git remote add space https://Pissaia92:$HF_TOKEN@huggingface.co/spaces/Pissaia92/chatbot-rag-autosservico
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$BRANCH" = "master" ]; then
            git push --force space master:main
          else
            git push --force space "$BRANCH":main
          fi
