name: Sync with Hugging Face Space

on:
  push:
    branches:
      - main 

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "cj.nord@yahoo.com"
          git config --global user.name "Pissaia92"
          git remote add space https://Pissaia92:$HF_TOKEN@huggingface.co/spaces/Pissaia92/chatbot-rag-autosservico
          git push --force space main
