name: Sync with Hugging Face Space

on:
  push:
    branches:
      - main
      - master

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Force push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote remove space || true
          git remote add space https://Pissaia92:$HF_TOKEN@huggingface.co/spaces/Pissaia92/chatbot-rag-autosservico

          # Detecta branch atual no GitHub
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Pushing $BRANCH -> main on Hugging Face"

          if [ "$BRANCH" = "master" ]; then
            git push --force space master:main
          else
            git push --force space main
          fi